### ISSUE TITLE
[IPFS] Flaky ipfs test

### ISSUE THREAD

**Issue by dongshu2013** [DeComX/pantheon#8]
ipfs.test.js fails randomly due to following error

```
FAIL src/ipfs/ipfs.test.js
  ● upload user

    Lock file is already being held

      at node_modules/proper-lockfile/lib/lockfile.js:68:47
      at callback (node_modules/graceful-fs/polyfills.js:295:20)

  ● upload user

    TypeError: Cannot read property 'files' of undefined

      12 | export const listAll = async (ipfs, dir) => {
      13 |   const files = [];
    > 14 |   for await (const file of ipfs.files.ls(dir)) {
         |                                 ^
      15 |     files.push(file.name);
      16 |   }
      17 |   return files;

      at listAll (src/ipfs/ipfs.js:14:33)
      at fileExists (src/ipfs/ipfs.js:21:23)
      at remove (src/ipfs/ipfs.js:26:24)
      at upload (src/ipfs/ipfs.js:37:9)
      at uploadProto (src/ipfs/ipfs.js:33:9)
      at Object.<anonymous> (src/ipfs/ipfs.test.js:55:9)

  ● upload user

    TypeError: Cannot read property 'stop' of undefined

      48 |
      49 | afterEach(async () => {
    > 50 |   await ipfsNode.stop();
         |                  ^
      51 | });
      52 |
      53 | it('upload user', async () => {

      at Object.<anonymous> (src/ipfs/ipfs.test.js:50:18)

  ● upload task

    Lock file is already being held

      at node_modules/proper-lockfile/lib/lockfile.js:68:47
      at callback (node_modules/graceful-fs/polyfills.js:295:20)

  ● upload task

    TypeError: Cannot read property 'files' of undefined

      12 | export const listAll = async (ipfs, dir) => {
      13 |   const files = [];
    > 14 |   for await (const file of ipfs.files.ls(dir)) {
         |                                 ^
      15 |     files.push(file.name);
      16 |   }
      17 |   return files;

      at listAll (src/ipfs/ipfs.js:14:33)
      at fileExists (src/ipfs/ipfs.js:21:23)
      at remove (src/ipfs/ipfs.js:26:24)
      at upload (src/ipfs/ipfs.js:37:9)
      at uploadProto (src/ipfs/ipfs.js:33:9)
      at Object.<anonymous> (src/ipfs/ipfs.test.js:71:9)
...
```

The reason is that the lockfile of IPFS is not released somehow. Retry normally works but we need a more elegant solution for this issue.

cc @Roger-Hong @neilzhu2

**Comment by dongshu2013** [comment]
IPFS.create() function accepts a repo option. Not sure if it will help. I'm checking.

**Comment by dongshu2013** [comment]
fixed by changing beforeEach to beforeAll in the test
